# Generated by Django 5.2.9 on 2026-05-12 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_monitor", "0007_species_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="观测纬度(y)"),
        ),
        migrations.AddField(
            model_name="observationrecord",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="优先用于首页观鸟记录定位；为空时回退到监测点位坐标",
                null=True,
                srid=4326,
                verbose_name="观测位置",
            ),
        ),
        migrations.AddField(
            model_name="observationrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="观测经度(x)"),
        ),
    ]
