# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_monitor', '0008_observationrecord_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObservationCache',
            fields=[
                (
                    'record',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='map_cache',
                        serialize=False,
                        to='app_monitor.observationrecord',
                        verbose_name='观测记录',
                    ),
                ),
                ('observation_time', models.DateField(db_index=True, verbose_name='观测日期')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(db_index=True, max_length=10, verbose_name='审核状态')),
                ('species_id_cached', models.IntegerField(db_index=True, verbose_name='物种ID')),
                ('species_name', models.CharField(db_index=True, max_length=100, verbose_name='物种中文名')),
                ('species_latin', models.CharField(blank=True, max_length=100, verbose_name='物种拉丁名')),
                ('species_protection', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='保护等级')),
                ('zone_id_cached', models.IntegerField(db_index=True, verbose_name='点位ID')),
                ('zone_name', models.CharField(db_index=True, max_length=100, verbose_name='点位名称')),
                ('transect_name', models.CharField(blank=True, max_length=100, verbose_name='样线名称')),
                ('longitude', models.FloatField(db_index=True, verbose_name='经度')),
                ('latitude', models.FloatField(db_index=True, verbose_name='纬度')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='图片地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页点位缓存',
                'verbose_name_plural': '首页点位缓存',
                'indexes': [
                    models.Index(fields=['status', 'observation_time'], name='map_cache_status_time_idx'),
                    models.Index(fields=['species_name', 'observation_time'], name='map_cache_species_time_idx'),
                    models.Index(fields=['zone_name', 'observation_time'], name='map_cache_zone_time_idx'),
                ],
            },
        ),
    ]
